/**
 * SEED DATA HELPER - Updated for separated StatusPekerjaan and StatusKonfirmasi
 * This shows the corrected seed structure
 */

export const SEED_PEKERJAAN = [
  {
    id: "PKJ-001",
    namaPekerjaan: "Perbaikan jaringan FH",
    status: "in_progress" as const,
    suratMasuk: "perbaikan_jaringan_FH.pdf",
    divisi: ["Infrastruktur Jaringan"],
    assignees: [
      {
        stafId: "U-D4-01",
        nama: "Nyoman Herman Ardike, S.T.",
        nip: "198801072012121001",
        jabatan: "Teknisi Jaringan",
        divisi: "Infrastruktur Jaringan",
        statusPekerjaan: "in_progress" as const,
        statusKonfirmasi: "accepted" as const,
      },
    ],
    lokasi: "Gedung Fakultas Hukum, Lantai 2",
    unitPeminta: "Fakultas Hukum",
    deskripsi: "Perbaikan infrastruktur jaringan di Fakultas Hukum Unila.",
    targetSelesai: "2026-07-10",
    suratTugas: null,
    suratStatus: undefined,
    catatan: null,
  },
  {
    id: "PKJ-002",
    namaPekerjaan: "Instalasi Switch Gedung B",
    status: "review" as const,
    suratMasuk: "instalasi_switch.pdf",
    divisi: ["Infrastruktur Jaringan"],
    assignees: [
      {
        stafId: "U-D4-02",
        nama: "Kasdi Pratama, A.Md.",
        nip: "199106152014021001",
        jabatan: "Teknisi Jaringan",
        divisi: "Infrastruktur Jaringan",
        statusPekerjaan: "in_progress" as const,
        statusKonfirmasi: "accepted" as const,
      },
    ],
    lokasi: "Gedung B, Lantai 2, Ruang Server",
    unitPeminta: "BAAK",
    deskripsi: "Pemasangan switch baru di gedung B lantai 2.",
    targetSelesai: "2026-07-20",
    suratTugas: "ST-PKJ-002.pdf",
    suratStatus: "published" as const,
    catatan: null,
  },
  {
    id: "PKJ-003",
    namaPekerjaan: "Update Firmware Router",
    status: "assigned" as const,
    suratMasuk: "firmware_router.pdf",
    divisi: ["Infrastruktur Jaringan"],
    assignees: [
      {
        stafId: "U-D4-03",
        nama: "Gontor Ganta Nama, S.T.",
        nip: "199307282017121002",
        jabatan: "Teknisi Infrastruktur",
        divisi: "Infrastruktur Jaringan",
        statusPekerjaan: "assigned" as const,
        statusKonfirmasi: "pending" as const,
      },
    ],
    lokasi: "Ruang NOC, Gedung Rektorat",
    unitPeminta: "Rektorat",
    deskripsi: "Update firmware seluruh router kampus ke versi terbaru.",
    targetSelesai: "2026-08-05",
    suratTugas: null,
    suratStatus: undefined,
    catatan: null,
  },
  {
    id: "PKJ-004",
    namaPekerjaan: "Monitoring Bandwidth Harian",
    status: "assigned" as const,
    suratMasuk: "monitoring_bw.pdf",
    divisi: ["Infrastruktur Jaringan"],
    assignees: [
      {
        stafId: "U-D4-04",
        nama: "Rahmad Junaidi",
        nip: "198903162015031001",
        jabatan: "Teknisi Jaringan",
        divisi: "Infrastruktur Jaringan",
        statusPekerjaan: "assigned" as const,
        statusKonfirmasi: "rejected" as const,
        alasanPenolakan: "Sedang sakit dan dirawat di rumah sakit",
      },
    ],
    lokasi: "Ruang NOC, Gedung Rektorat",
    unitPeminta: "BPKHM",
    deskripsi: "Monitoring penggunaan bandwidth harian seluruh gedung.",
    targetSelesai: "2026-06-15",
    suratTugas: null,
    suratStatus: undefined,
    catatan: "Staf penolak perlu diganti segera.",
  },
];

export const SEED_PROYEK = [
  {
    id: "PRY-001",
    namaProyek: "Website KKN Unila",
    status: "in_progress" as const,
    statusKonfirmasi: "accepted" as const,
    suratMasuk: "kkn.pdf",
    divisi: ["Pengembangan dan Inovasi Teknologi Informasi", "Manajemen dan Integrasi Sistem Informasi"],
    lokasi: "Gedung UPA TIK, Lantai 3",
    unitPeminta: "LPPM",
    staf: "Nurrahma, S.Kom., M.T.",
    stafId: "U-D1-01",
    nip: "199001052015042001",
    jabatan: "Analis Sistem Informasi",
    assignees: [
      {
        stafId: "U-D1-01",
        nama: "Nurrahma, S.Kom., M.T.",
        nip: "199001052015042001",
        jabatan: "Analis Sistem Informasi",
        divisi: "Pengembangan dan Inovasi Teknologi Informasi",
        statusPekerjaan: "in_progress" as const,
        statusKonfirmasi: "accepted" as const,
        masukSurat: true,
      },
    ],
    deskripsi: "Pengembangan website portal KKN Universitas Lampung.",
    targetSelesai: "2026-07-20",
    suratTugas: "ST-PRY-001.pdf",
    suratStatus: "published" as const,
    catatan: null,
  },
  {
    id: "PRY-002",
    namaProyek: "Sistem Informasi Akademik",
    status: "review" as const,
    statusKonfirmasi: "accepted" as const,
    suratMasuk: "sia.pdf",
    divisi: ["Pengembangan dan Inovasi Teknologi Informasi"],
    lokasi: "Gedung UPA TIK, Lantai 2",
    unitPeminta: "BAAK",
    staf: "Nurrahma, S.Kom., M.T.",
    stafId: "U-D1-01",
    nip: "199001052015042001",
    jabatan: "Analis Sistem Informasi",
    assignees: [
      {
        stafId: "U-D1-01",
        nama: "Nurrahma, S.Kom., M.T.",
        nip: "199001052015042001",
        jabatan: "Analis Sistem Informasi",
        divisi: "Pengembangan dan Inovasi Teknologi Informasi",
        statusPekerjaan: "review" as const,
        statusKonfirmasi: "accepted" as const,
        masukSurat: true,
      },
    ],
    deskripsi: "Pengembangan SIA terbaru dengan fitur mobile.",
    targetSelesai: "2026-08-30",
    suratTugas: "ST-PRY-002.pdf",
    suratStatus: "published" as const,
    catatan: null,
  },
  {
    id: "PRY-003",
    namaProyek: "Portal E-Learning",
    status: "assigned" as const,
    statusKonfirmasi: "pending" as const,
    suratMasuk: "elearning.pdf",
    divisi: ["Pengembangan dan Inovasi Teknologi Informasi"],
    lokasi: "Gedung UPA TIK, Lantai 1",
    unitPeminta: "Rektorat",
    staf: "Atika Istiqomah, S.Kom., M.T.",
    stafId: "U-D3-01",
    nip: "199107182016042002",
    jabatan: "Pengembang Perangkat Lunak",
    assignees: [
      {
        stafId: "U-D3-01",
        nama: "Atika Istiqomah, S.Kom., M.T.",
        nip: "199107182016042002",
        jabatan: "Pengembang Perangkat Lunak",
        divisi: "Pengembangan dan Inovasi Teknologi Informasi",
        statusPekerjaan: "assigned" as const,
        statusKonfirmasi: "pending" as const,
        masukSurat: true,
      },
    ],
    deskripsi: "Pembuatan portal e-learning terintegrasi SSO.",
    targetSelesai: "2026-09-15",
    suratTugas: null,
    suratStatus: undefined,
    catatan: null,
  },
];
